cluster_name: tali-cluster

project: tali-multi-modal
zone: us-central1-f

external_compute_ips: false
google_app_cred_path: /slurm/scripts/service_account.key

shared_vpc_host_project: tali-multi-modal
vpc_subnet: tali-cluster-network

slurm_cmd_path: /usr/local/bin
log_dir: /var/log/slurm

compute_node_scopes:
- https://www.googleapis.com/auth/monitoring.write
- https://www.googleapis.com/auth/logging.write
- https://www.googleapis.com/auth/cloud-platform

compute_node_service_account: tali-multi-modal@tali-multi-modal.iam.gserviceaccount.com

update_node_addrs: true

network_storage: []
login_network_storage: []

instance_defs:
  worker-small:
    machine_type: a2-highgpu-1g
    zone: us-west1-b
    image: projects/schedmd-slurm-public/global/images/family/schedmd-slurm-21-08-4-debian-10
    image_hyperthreads: true
    compute_disk_size_gb: 350
    compute_disk_type: pd-standard
    compute_labels: {}
    cpu_platform: null
    gpu_count: 1
    gpu_type: nvidia-tesla-a100
    enable_placement: false
    exclusive: false
    instance_template: projects/tali-multi-modal/global/instanceTemplates/gpu-small-node
    network_storage: []
    preemptible_bursting: true
    regional_capacity: false
    regional_policy: {}
    vpc_subnet: tali-cluster-network
    compute_node_service_account: tali-multi-modal@tali-multi-modal.iam.gserviceaccount.com
    compute_node_scopes: ["https://www.googleapis.com/auth/cloud-platform"]
